#!/bin/bash

MAX=`cat /etc/samba/smb.conf|grep path | wc -l`
m=1
count=0
detail='"data":['
for (( i = 0; i < MAX ; i ++ ))
do
	dir=`cat /etc/samba/smb.conf|grep '\['|sed -n $m'p'`
	if [ "$dir" = "[global]" ]
	then
		let m=m+1
	fi
	dirs[i]=`cat /etc/samba/smb.conf|grep '\['|sed -n $m'p'`
	let m=m+1
	let n=i+1
	paths[i]=`cat /etc/samba/smb.conf|grep path|sed -n $n'p'|cut -d ' ' -f3`
	status[i]=`cat /etc/samba/smb.conf|grep browseable|sed -n $n'p'|cut -d ' ' -f3`
	availables[i]=`cat /etc/samba/smb.conf|grep available|sed -n $n'p'|cut -d ' ' -f3`
	hosts[i]=`cat /etc/samba/smb.conf|grep "host"|sed -n $n'p'|cut -d '=' -f2`
	masks[i]=`cat /etc/samba/smb.conf|grep 'create mask'|sed -n $n'p'|cut -d ' ' -f4`
	alls[i]=`df -h ${paths[i]}|sed -n '2p'|awk '{print $2}'`
	useables[i]=`df -h ${paths[i]}|sed -n '2p'|awk '{print $4}'`
	users[i]=`stat -c %U ${paths[i]}`
	groups[i]=`stat -c %G ${paths[i]}`
	#echo ${paths[$i]}
	#echo ${status[$i]}
	#echo ${masks[$i]}
	#echo ${alls[$i]}
	#echo ${hosts[i]:2}
	#echo ${useables[$i]}
	#echo ${users[$i]}
	#echo ${groups[$i]}
	detail=${detail}'{"id":"'$n'" , "dir":"'${dirs[$i]}'" , "path":"'${paths[$i]}'" , "browseable":"'${status[$i]}'" , "available":"'${availables[$i]}'" , "hostallow":"'${hosts[$i]:1}'" , "mask":"'${masks[$i]}'" , "all":"'${alls[$i]}'" , "useable":"'${useables[$i]}'" , "user":"'${users[$i]}'" , "group":"'${groups[$i]}'"},'
    let count=n
done
detail=${detail::-1}']}'
detail='{"code": 0, "msg": "", "count": '${count}', '${detail}
echo ${detail}
